BEGIN;
--
-- Create model User
--
CREATE TABLE "users" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "username" varchar(255) NOT NULL, "password" varchar(100) NOT NULL);
COMMIT;
